#!/bin/bash
## Punch! - CLI interface to Emacs ORG-mode files for clocks 2014 by jramb
## Background: I am a Vimmer, but there is one thing that rocks about Emacs: the ORG mode
## This script reduces my need to fire up Emacs to once a month when I assemble my
## Time reports...
########################

#set -x
set -e
#set -u
today="$(date +%F)"

shopt -s nocasematch   # case insensitve matching

if [[ ! -f "$CLOCKFILE" ]]; then
  echo "You need to set the environmen variable CLOCKFILE (pointing to an existing file)"
  exit 2
fi

copyfile="${CLOCKFILE}.copy"
backupfile="${CLOCKFILE}.backup-$(date +%Y%m%d)"
[[ -f "$copyfile" ]] && rm "$copyfile"

backIFS=$IFS
IFS=
verbose=

date_match="[0-9]{4}-[0-9]{2}-[0-9]{2}"
time_match="[0-9]{1,2}:[0-9]{2}"
duration_match="-?[0-9]+:[0-9]{2}"
date_time_match="($date_match [[:alpha:]]{1,3} $time_match)"
clock_match="CLOCK: \[$date_time_match\](--\[$date_time_match\]( =>[[:space:]]*($duration_match)))?"
struct_match='^((\*+)[[:space:]]+)(.*)$'

usage() {
  cat << EOF_USAGE
'punch' 2014 by jramb
---------------------
Usage: $(basename $0) <command> [<opt>]

commands:
  h[elp]      Show this message
  ls          lists tasks in clock filej
  in <task>   Check in (start timer) for task (also stops all other timers)
  out         Check out (stops ALL timers)

You need to set the environmen variable CLOCKFILE (pointing to an existing file)
EOF_USAGE
}

to_epoc() {
  echo "$(date -d "$1" "+%s")"
}

secs_to_time() {
  local elapsed=$1
  local sign=
  let "elapsed_minutes=elapsed/60"
  if (( elapsed_minutes < 0 )); then
    let "elapsed_minutes = -elapsed_minutes"
    sign=-
  fi
  let "elapsed_hours=elapsed_minutes/60"
  let "elapsed_minutes -= elapsed_hours * 60"
  as_time=$(printf "%s:%02d" "$sign$elapsed_hours" $elapsed_minutes)
  echo "$as_time"
}

duration_since() {
  now_is=${2:- $(date +%s)}
  secs_to_time $(( $now_is - $(to_epoc "$1") ))
}

conclude_time() {
  now_is="$(date "+%F %a %R")"
  duration="$(duration_since "$1" $(to_epoc "$now_is"))"
  echo "CLOCK: [${1}]--[$now_is] => $(printf "%5s" "$duration")"
}

clock_info() {
  local t_from=${BASH_REMATCH[1]}
  local t_to=${BASH_REMATCH[3]}
  local is_today=0
  if [[ -n "$t_to" ]]; then
    local t_to_e=$(to_epoc "$t_to")
    [[ "$t_to" =~ "$today" ]] && is_today=1
  else
    is_today=1
    local t_to_e=$(date +%s)
  fi
  if (( is_today )); then
    local t_from_e=$(to_epoc "$t_from")
    echo $(( t_to_e - t_from_e )) # $t_to_e - $_from_e
  fi
}

cmd_structure() {
  local line
  cat "$CLOCKFILE" |
  while read line ; do
    if [[ "$line" =~ $struct_match ]]; then
      echo "$line"
    fi
  done;
}

cmd_times() {
  local line
  cat "$CLOCKFILE" |
  while read line ; do
    if [[ "$line" =~ $clock_match ]]; then
      echo "$line >>> $(clock_info)"
    fi
  done;
}

make_backup() {
  if [[ ! -f "$backupfile" ]]; then
    mv "$CLOCKFILE" "$backupfile"
  fi
}


analyze() {
  section="$1"
  section_found=
  last_time=0
  is_running=0
  cat "$CLOCKFILE" |
  {
    while read line; do
      if [[ "$line" =~ $struct_match ]]; then
        current=${BASH_REMATCH[3]}
        if [[ ! -z "$section" ]]; then
          if [[ $current =~ "$section" ]]; then
            if [[ -z "$section_found" ]]; then
              section_found="$current"
            else
              echo "ERROR: Duplicate section match: '$section_found' and '$current'" >&2
              exit 99 # Found duplicate structure
            fi
          fi
        fi
      fi
      if [[ "$line" =~ $clock_match ]]; then
        this_time=$(to_epoc ${BASH_REMATCH[1]})
        if (( this_time > last_time )); then
          last_time=$this_time
        fi
        if [[ ! -n "${BASH_REMATCH[2]}" ]]; then
          is_running=1
        fi
      fi
    done 
    echo "$last_time:$is_running:$section_found"
  }
}

running() {
  cat "$CLOCKFILE" |
  {
    local current_cnt=0
    local is_running=0
    while read line ; do
      if [[ "$line" =~ $struct_match ]]; then
        indent=${#BASH_REMATCH[1]} # indent size
        if (( current_cnt )); then
          echo "$current $(secs_to_time $current_cnt)"
          current_cnt=0
        fi
        is_running=0
        current=${BASH_REMATCH[3]}
      fi
      if [[ "$line" =~ $clock_match ]]; then
        local secs=$(clock_info)
        if (( secs )); then
          (( current_cnt = current_cnt + secs ))
        fi
        if [[ ! -n "${BASH_REMATCH[2]}" ]]; then
          #echo "$current running" >&2
          #line=$(printf "%${indent}s%s\n" '' $(conclude_time "${BASH_REMATCH[1]}"))
          #echo "$line [RUNNING]" >&2
          is_running=1
          current="* $current"
        fi
      fi
    done;
    (( current_cnt )) && echo "$current $(secs_to_time $current_cnt)"
  }
}

prompt() {
  cat "$CLOCKFILE" |
  while read line ; do
    if [[ "$line" =~ $struct_match ]]; then
      current=${BASH_REMATCH[3]}
    fi
    if [[ "$line" =~ $clock_match ]]; then
      if [[ ! -n "${BASH_REMATCH[2]}" ]]; then
        echo "$current: $(duration_since "${BASH_REMATCH[1]}")\n"
      fi
    fi
  done;
}

check_out() {
  {
    while read line
    do
      # check if current line is a structure line (starting with an asterix)
      if [[ "$line" =~ $struct_match ]]; then
        indent=${#BASH_REMATCH[1]} # indent size
        current=${BASH_REMATCH[3]}
      fi
      if [[ ! -z "$line" ]]; then
        if [[ "$line" =~ $clock_match && ! -n "${BASH_REMATCH[2]}" ]]; then
          line=$(printf "%${indent}s%s\n" '' $(conclude_time "${BASH_REMATCH[1]}"))
          echo "$current checked out" >&2
          echo "$line" >&2
        fi
        echo "$line"
      fi
    done 
  } < "$CLOCKFILE" >"$copyfile"
  make_backup
  mv -f "$copyfile" "$CLOCKFILE"
}

check_in() {
  local section="$1"
  local check=$(analyze "$1")
  (( $? > 0 )) && return 
  if [[ -z "$section" ]]; then
    echo "Need a section to check in"
    cmd_structure
    exit 2
  fi
  {
    now_is=
    while read line
    do
      print_line=1
      # check if current line is a structure line (starting with an asterix)
      if [[ "$line" =~ $struct_match ]]; then
        indent=${#BASH_REMATCH[1]} # indent size
        current=${BASH_REMATCH[3]}
        if [[ $current =~ "$section" && -z "$now_is" ]]; then
          now_is="$(date "+%F %a %R")"
          echo "$line" # original
          line=$(printf "%${indent}s%s\n" '' "CLOCK: [$now_is]")
          echo "$line" # the new one
          echo "$current checked in" >&2
          echo "$line" >&2
          unset line
          print_line=0
        fi
      fi
      if (( print_line )); then
        if [[ "$line" =~ $clock_match && ! -n "${BASH_REMATCH[2]}" ]]; then
          line=$(printf "%${indent}s%s\n" '' $(conclude_time "${BASH_REMATCH[1]}"))
          echo "$current checked out" >&2
          echo "$line" >&2
        fi
        echo "$line"
      fi
    done 
    #echo "$current --> $now_is" >&2
  } < "$CLOCKFILE" >"$copyfile"
  make_backup
  #diff "$copyfile" "$CLOCKFILE"
  mv -f "$copyfile" "$CLOCKFILE"
}


edit() {
  if [[ ! -z "$EDITOR" ]]; then
    $EDITOR $CLOCKFILE
  fi
}



while true; do
  case "$1" in
    str*|ls)
      cmd_structure
      ;;
    ti*)
      cmd_times
      ;;
    ed*)
      edit
      ;;
    sh*) # show
      cat "$CLOCKFILE"
      ;;
    in|sta*)
      check_in $2
      ;;
    diff)
      if [[ -f "$backupfile" ]]; then
        diff "$backupfile" "$CLOCKFILE"
      else
        echo 'No changes yet'
      fi
      ;;
    out|sto*)
      check_out
      ;;
    h*)
      usage
      exit 1
      ;;
    ru*)
      running
      ;;
    pro*)
      prompt
      exit 0
      ;;
    *)
      running
      echo "Run '$(basename "$0") help' for more info" >&2
      ;;
  esac
  shift
  exit 0
done

